const ClubInfoHome=[
    {   id:1,
        name:"Club of Knowledge",
        info:"Club of Knowledge is a knowledge-sharing platform dedicated to fostering intellectual growth and thoughtful learning among students. The club actively supports foundational courses such as Art of Happiness and Psychology of Everyday Life through engaging discussions, interactive workshops, and curated learning resources. By creating a collaborative and inclusive environment, the club encourages students to explore concepts related to mental well-being, self-awareness, and personal development beyond the classroom.",
        cat:"Literary",
        url:"https://i.pinimg.com/1200x/1a/8a/25/1a8a25012d74b1616574ad8e5b4e9b50.jpg",
        link:"https://www.skit.ac.in/student-corner/students-s-life.html?layout=view&id=1529",
       
    },
    {  id:2,
        name:"Dance Club",
        info:"Dance is the most joyous embellishments of a creative soul. Dancing to the enchanting spell of music unleashes a perfect union of expression & joy. SKIT’s Dance Club provides a platform to this expression where students tap their feet to the tunes of various styles of dancing. This club provides an opportunity to better the dancer in students through constant engagement by organizing intra & inter college competitions and also through workshops conducted by the club.",
        cat:"Cultural",
         url:"./images/DanceClub.jpeg",
         link:"https://www.skit.ac.in/student-corner/students-s-life.html?layout=view&id=283",
        
    },
     {  id:3,
        name:"Docu Drama Club",
        info:"The club thrives on a vibrant spirit of competition that fuels individual growth and excellence. Each event is designed to be innovative and engaging, offering participants a unique opportunity to sharpen their skills. With a focus on personal as well as professional development, these competitions foster both creativity and mastery. Notable events include Market It, Figure of 100, Typing Challenge, Figma Design, Debate Competitions, Leadership Training Sessions, Body Language Workshops and more—each carefully crafted to push participants to their fullest potential.",
        cat:"Cultural",
         url:"https://i.pinimg.com/1200x/e9/f5/60/e9f560007cbbdd6f90ec105e7bb59c89.jpg",
         link:"https://www.skit.ac.in/student-corner/students-s-life.html?layout=view&id=250",
       
    },
     {  id:4,
        name:"Eco Friends Club",
        info:"Eco-friendly literally means earth-friendly or not harmful to the environment. This term most commonly refers to products that contribute to green living or practices that help conserve resources like water and energy. EFC club mainly engage club members in eco-friendly habits or practices by being more conscious of how we use resources.",
        cat:"Social",
          url:"https://i.pinimg.com/1200x/4a/84/b0/4a84b0e5f37fd40f5b855f4271033dbe.jpg",
          link:"https://www.skit.ac.in/student-corner/students-s-life.html?layout=view&id=26",
          
    },
     {  id:5,
        name:"Embedded Club",
        info:"Embedded Club strives to impart enthusiasm and passion for electronics and allied fields among students of ECE. The club aims to uncover those key topics that are not part of the curriculum or just grazed upon by the syllabus. The functions of the club are to deal from basics of electronics to the peak of it. This club, for sure, will help the students not only in their studies but also in their career.",
        cat:"Tech",
          url:"https://i.pinimg.com/736x/8f/37/14/8f3714fb166f6d1f0cd001719ad38095.jpg",
          link:"https://www.skit.ac.in/student-corner/students-s-life.html?layout=view&id=1534",
         
    },
     {  id:6,
        name:"Fine Arts & Crafts Club",
        info:"Fine Arts and Crafts club was founded in 2016 and has been a platform for the students of SKIT to showcase their artistic skills ever since. The club focuses on helping the students to grow and learn new techniques which enhances their skills to express more through their artwork. We promote and nurture creativity and constantly support the artists to strive for the betterment of their skills.Our club also hosts an annual art exhibition “RANG” during PRAVAH, the annual college fest. RANG is a platform for all the artists to display their artwork for everyone to appreciate.",
        cat:"Artistic",
          url:"https://i.pinimg.com/1200x/02/c8/30/02c8301cc32ce79dce58586ce95a5d2e.jpg",
          link:"https://www.skit.ac.in/student-corner/students-s-life.html?layout=view&id=1521",
        
    },
     {  id:7,
        name:"Music Club",
        info:"Music is the language of soul. The music club encourages students to showcase their talents in music- instrumental as well as in vocal. Music club provides a platform to individual to participate in various inter and intra college competition. In a regular club activity students continued to learn and practice by organizing jamming sessions.",
        cat:"Cultural",
          url:"https://i.pinimg.com/1200x/e1/18/d8/e118d8bad3d74f6832f33a412aa46069.jpg",
          link:"https://www.skit.ac.in/student-corner/students-s-life.html?layout=view&id=27",
        
    },
     {  id:8,
        name:"NSS Club",
        info:"National Service Scheme club was established at SKIT in the year 2009. The club strives to bring improvements in the field of social welfare. This club mainly serves the villages. The club organizes various activities for the poor uneducated people. It is all because of the students of the club that the goals and objectives of the club are met.",
        cat:"Social",
          url:"https://i.pinimg.com/1200x/a2/0d/6b/a20d6be9b14a1f3186c6e8a3f9ad1120.jpg",
          link:"https://www.skit.ac.in/student-corner/students-s-life.html?layout=view&id=28",
         
    },
     {  id:9,
        name:"Renewable Energy Club",
        info:"Renewable Energy Club incepted in 2007, in Swami Keshvanand Institute of Technology under the program initiative by Rajasthan Renewable Energy Corporation Limited, Jaipur and Ministry of Non-conventional Energy Resources. Club is helping the students to make them aware about various renewable energy resources and techniques with the help of a number of programs and quizzes – like celebrating Akshay Urza Diwas annually, Paper presentation and Poster making competition, debates, etc.",
        cat:"Tech",
          url:"https://i.pinimg.com/1200x/f9/a9/da/f9a9dabd4871499a0204e21709c65ea5.jpg",
          link:"https://www.skit.ac.in/student-corner/students-s-life.html?layout=view&id=491",
        
    },
     {  id:10,
        name:"Robotics Club",
        info:"The Robotics Club is a community of students who derive pleasure in creating robots that may even be capable of working without human intervention. Each member of this family is provided insight into mechanical engineering, basic electronics and informatory aids besides the indispensable guidance of experienced members. The club supports and fosters interest in various aspects related to robotics in particular, mechanical design through workshops and projects. Robo-geeks are provided with a workspace, tools and other amenities to let their imagination loose.",
        cat:"Tech",
          url:"https://i.pinimg.com/736x/ed/cd/c8/edcdc86bde394077d3d3f6930c61a54d.jpg",
          link:"https://www.skit.ac.in/student-corner/students-s-life.html?layout=view&id=248",
         
    },

     {  id:11,
        name:"Science and Technology Club",
        info:"Science and Technology club believes in the saying,Everything is theoretically impossible until it is done.Science and Technology Club is a one stop destination for all the innovative and creative brains who really want to make a difference. We provide an engaging platform for the budding engineers where everyone will evolve in a mission to IMAGINE, INVENT and INSPIRE.The club organizes various activities and workshops under experienced trainers.There is no limitation to only technical activities but also we organize intra and inter-level competition.",
        cat:"Tech",
        url:"https://i.pinimg.com/736x/60/f2/ef/60f2ef08574f622ad6ca4fb616b23446.jpg",
        link:"https://www.skit.ac.in/student-corner/students-s-life.html?layout=view&id=603",
        
    },

     {  id:12,
        name:"Spic Macay Heritage Club",
        info:"SPIC MACAY, the Society for the Promotion of Indian Classical Music And Culture Amongst Youth is a voluntary youth movement which promotes intangible aspects of Indian cultural heritage by promoting Indian classical music, classical dance, folk music, yoga, meditation, crafts and other aspects of Indian culture.",
        cat:"Cultural",
          url:"https://i.pinimg.com/736x/1d/d4/9d/1dd49d42a79e1ddb6f998a12a8e321b8.jpg",
          link:"https://www.skit.ac.in/student-corner/students-s-life.html?layout=view&id=485",
          
    } ,
    {  id:13,
        name:"Tech Innova Club",
        info:"Tech Innova is a technical society of CSE & IT departments, in its broadest sense encompasses all aspects of computing technology. It Started in 2012. We are honored to have a privilege of 700+ students till now. We hosts various technical events like software engineering and development, computer networking and communications, Web technologies, computer security, database management, and digital media technologies related events.",
        cat:"Tech",
          url:"https://i.pinimg.com/736x/48/83/65/488365efd52ad5e90b41c7de8bd6c267.jpg",
          link:"https://www.skit.ac.in/student-corner/students-s-life.html?layout=view&id=1532",
         
    },

     {  id:14,
        name:"Toastmasters Club",
        info:"oastmasters International is a non-profit educational organization that teaches public speaking and leadership skills through a worldwide network of clubs. Headquartered in Englewood, Colo., the organization's membership exceeds 358,000 in more than 16,800 clubs in 143 countries. Since 1924, Toastmasters International has helped people from diverse backgrounds become more confident speakers, communicators, and leaders. Toastmasters follows the curriculum called The Pathways. This learning experience is Toastmasters' education program. ",
        cat:"Literary",
          url:"https://i.pinimg.com/1200x/c8/ea/e7/c8eae70227b5043beaf11832e53b2c8c.jpg",
          link:"https://www.skit.ac.in/student-corner/students-s-life.html?layout=view&id=59",
          
    } ,
    {  id:15,
        name:"Yoga & Meditation Club",
        info:"Yogic practices enhance muscular strength and body flexibility, promote and improve respiratory and cardiovascular function, promote recovery from and treatment of addiction, reduce stress, anxiety, depression, and chronic pain, improve sleep patterns, and enhance overall well-being",
        cat:"Social",
          url:"https://i.pinimg.com/736x/eb/30/86/eb3086306d166fa2172b077d8ab239e7.jpg",
          link:"https://www.skit.ac.in/student-corner/students-s-life.html?layout=view&id=1527",
          
    },
     {  id:16,
        name:"Maths N Rates Club",
        info:"Maths & Rates Club is a community of students interested in Analysis or technicality in general. All the students of any branch are welcome in the club. Maths & Rates Club helps an individual to prepare for Placements, provides Guest math hunts, poster making and many more tech events.",
        cat:"Literary",
          url:"https://i.pinimg.com/1200x/95/cf/02/95cf0287c03735f11330c0f805657aa3.jpg",
          link:"https://www.skit.ac.in/student-corner/students-s-life.html?layout=view&id=1525",
        
    },
     {  id:17,
        name:"CodeFiesta Club",
        info:"CodeFiesta is a vibrant college tech club-where technology meets creativity…!!! Explore Google developer tools, collaborate with fellow students, learn alongside peers, and expand your coding expertise by contributing to meaningful projects for local businesses and our community. Whether you're an aspiring developer or tech enthusiast, come be a part of our collaborative, growth-focused community.",
        cat:"Tech",
          url:"https://i.pinimg.com/1200x/d6/f2/77/d6f2778e4a9c4b3ea4a76f09392901ba.jpg",
          link:"https://www.skit.ac.in/student-corner/students-s-life.html?layout=view&id=1518",
          
    },
     {  id:18,
        name:"Dynamic Club",
        info:"The club thrives on a vibrant spirit of competition that fuels individual growth and excellence. Each event is designed to be innovative and engaging, offering participants a unique opportunity to sharpen their skills. With a focus on personal as well as professional development, these competitions foster both creativity and mastery. Notable events include Market It, Figure of 100, Typing Challenge, Figma Design, Debate Competitions, Leadership Training Sessions, Body Language Workshops and more—each carefully crafted to push participants to their fullest potential.",
        cat:"Literary",
          url:"https://i.pinimg.com/736x/21/b1/ff/21b1ff7f1e88515f5fbc99601abc69cc.jpg",
          link:"https://www.skit.ac.in/student-corner/students-s-life.html?layout=view&id=1623",
          
    },
     {  id:19,
        name:"Unnat Bharat Abhiyan Club",
        info:"Unnat Bharat Abhiyan is inspired by the vision of transformational change in rural development processes by leveraging knowledge institutions to help build the architecture of an Inclusive India and to have a paradigm shift in academic and research programs of the country. The Mission of Unnat Bharat Abhiyan cell skit is to enable our institution to work with the people of rural India in identifying development challenges and evolving appropriate solutions for accelerating sustainable growth.",
        cat:"Social",
          url:"https://i.pinimg.com/1200x/59/b6/1c/59b61c3f1da597576a180af5527d8adb.jpg",
          link:"https://www.skit.ac.in/student-corner/students-s-life.html?layout=view&id=1622",
          
    },
     {  id:20,
        name:"SKIT Mun Club",
        info:"Model United Nations is one of the most popular ways to learn about the workings of the United  Nations. Conferences are organized by hundreds of educational institutions at all levels to  engage young students in diplomatic debates and conversations that resemble those at the  United Nations. It is often the first time that students are exposed to international affairs.",
        cat:"Literary",
          url:"https://i.pinimg.com/1200x/85/23/7f/85237fa37b293867a6a34326c0cd6893.jpg",
          link:"https://www.skit.ac.in/student-corner/students-s-life.html?layout=view&id=1624",
          
    },
     {  id:21,
        name:"SKIT Readers Club",
        info:"Skit Reader's Club is a platform which provides people with an opportunity to feature themselves as a speaker on the novels of their own interest, to promote reading on a greater level and make books interesting to talk about.",
        cat:"Literary",
          url:"https://i.pinimg.com/736x/67/11/20/67112044f484e15c59cf5e6e7d2d97a7.jpg",
          link:"https://www.skit.ac.in/student-corner/students-s-life.html?layout=view&id=1528",
         
    },
     {  id:22,
        name:"SKIT Gramothan Club",
        info:"Skit Gramothan Club is dedicated towards the improvement of the less priviledged, focusing on women and children, through developing mechanism aiming at service delivery and capacity building. This club organises charitable events to provide clothes, books and other necessities to people living in slum areas and villages. This clubs aims to create an environment that safeguards the life, dreams and aspirations of individuals going through unfavourable chain of circumstances, to ignite a spark for better change.",
        cat:"Social",
          url:"https://i.pinimg.com/1200x/76/99/1e/76991e67a7d1812241f3c94ad303ab94.jpg",
          link:"https://www.skit.ac.in/student-corner/students-s-life.html?layout=view&id=1531",
          
    },
     {  id:23,
        name:"Sustainability Champions Club",
        info:"The club is committed to promoting environmental awareness and encouraging responsible actions toward nature. It actively works to reduce waste and support sustainable practices through campaigns, initiatives, and community participation. By raising awareness about climate change and advocating for informed policy changes, the club aims to inspire long-term impact. In alignment with the Sustainable Development Goals (SDGs) proposed by the United Nations, the club strives to contribute meaningfully to sustainable development and a greener future.",
        cat:"Social",
          url:"https://i.pinimg.com/736x/a8/e5/c5/a8e5c5f756ad1179e194bc3205d8b144.jpg",
          link:"https://www.skit.ac.in/student-corner/students-s-life.html?layout=edit&id=1653",
         
    },
      {  id:24,
        name:"Competitative Programming Club",
        info:"The club aims to enhance creative thinking and strengthen problem-solving skills by guiding students to design effective solutions for computational challenges. It focuses on helping members acquire state-of-the-art technical skills required for the programmatic implementation of these solutions using modern tools and technologies. Through competitive coding events, practice sessions, and peer learning, the club fosters a focused learning environment for students preparing for careers in leading IT companies.",
        cat:"Tech",
          url:"https://i.pinimg.com/736x/2d/a0/c3/2da0c357c3a068b33bebe7a6595aa364.jpg",
          link:"https://www.skit.ac.in/student-corner/students-s-life.html?layout=edit&id=1654",
         
    },
      {  id:25,
        name:"Electric Vehicle Club",
        info:"The Electric Vehicle Club is dedicated to discussing and learning about emerging technologies in the field of electric mobility. The club encourages students to work on hands-on projects related to electric vehicles, battery systems, and sustainable transportation. Through collaborative learning, members gain practical insights into real-world EV applications. The club also promotes innovation, research, and technical skill development in clean energy solutions. By engaging in projects and discussions, the club aims to prepare students for the future of sustainable mobility.",
        cat:"Tech",
          url:"https://i.pinimg.com/1200x/c6/63/87/c66387c72fc9a604f4cec37686a5ea1b.jpg",
          link:"https://www.skit.ac.in/student-corner/students-s-life.html?layout=edit&id=1656",
         
    },
      {  id:26,
        name:"IBM Skills Build Clubs",
        info:"The IBM SkillsBuild Club focuses on empowering students with industry-relevant digital skills. It provides learning opportunities in areas such as cloud computing, AI, data science, and cybersecurity through IBM-curated resources. The club encourages hands-on practice and project-based learning. Students gain exposure to real-world problem solving aligned with industry needs. The club aims to enhance employability and career readiness.",
        cat:"Tech",
          url:"https://i.pinimg.com/736x/26/26/f6/2626f652abccbf2bcc705b394e8bdd04.jpg",
          link:"https://www.skit.ac.in/student-corner/students-s-life.html?layout=view&id=1529",
          
    },
      {  id:27,
        name:"AWS Acadmey Club",
        info:"The AWS Academy Club is dedicated to building strong foundations in cloud computing using Amazon Web Services. It offers structured learning paths covering cloud architecture, storage, security, and deployment. Members gain practical experience through labs and real-world use cases. The club prepares students for AWS certifications and cloud-based careers. It promotes innovation and cloud-first thinking.",
        cat:"Tech",
          url:"https://i.pinimg.com/736x/23/11/2e/23112ee11a68a60344adad9250589d5b.jpg",
          link:"https://www.skit.ac.in/student-corner/students-s-life.html?layout=view&id=1529",
          
    },
      {  id:28,
        name:"Hip Hop Hive Club",
        info:"Hip Hop Hive Club provides a creative platform for students passionate about rap, hip-hop culture, and lyrical expression. The club encourages songwriting, freestyle sessions, and performance practice. It helps members develop confidence, rhythm, and storytelling skills. Through workshops and performances, students explore music as a form of self-expression. The club celebrates creativity, individuality, and artistic freedom.",
        cat:"Cultural",
          url:"https://i.pinimg.com/736x/34/c1/6a/34c16a68287472dfb61678ab02d76845.jpg",
          link:"https://www.skit.ac.in/student-corner/students-s-life.html?layout=view&id=1529",
          
    },
      {  id:29,
        name:"AI Nexus Club",
        info:"AI Nexus Club focuses on exploring the rapidly evolving field of Artificial Intelligence and Machine Learning. It encourages learning through discussions, projects, and hands-on experimentation with AI tools. Members work on real-world problem statements using intelligent systems. The club promotes innovation, research mindset, and ethical AI awareness. It prepares students for future AI-driven industries.",
        cat:"Tech",
          url:"https://i.pinimg.com/736x/29/4d/36/294d3659a81c2462fc701e9158a34ea2.jpg",
          link:"https://www.skit.ac.in/student-corner/students-s-life.html?layout=view&id=1529",
         
    },
      {  id:30,
        name:"Infosys Springboard Club",
        info:"The Infosys Springboard Club aims to bridge the gap between academic learning and industry expectations. It provides access to high-quality learning resources in technology, soft skills, and professional development. The club encourages self-paced and guided learning through structured programs. Students gain exposure to real-world business and technical skills. The club supports career growth and lifelong learning.",
        cat:"Literary",
          url:"https://i.pinimg.com/736x/67/2d/b2/672db25ccef05345a573ce1ec4dd486d.jpg",
          link:"https://www.skit.ac.in/student-corner/students-s-life.html?layout=view&id=1529",
        
    },
      {  id:31,
        name:"Google Student Ambassador Club",
        info:"The Google Student Ambassador Club connects students with Google’s tools, technologies, and innovation culture. It promotes learning through workshops, events, and peer-to-peer knowledge sharing. Members act as a bridge between Google and the student community. The club encourages leadership, community building, and technical awareness. It helps students stay updated with the latest trends in technology.",
        cat:"Tech",
          url:"https://i.pinimg.com/1200x/dd/d4/d5/ddd4d5973b63bf6eec3ffb192107c952.jpg",
          link:"https://www.skit.ac.in/student-corner/students-s-life.html?layout=view&id=1529",
         
    },

      {  id:32,
        name:"Nirman Club",
        info:"The objective of the NIRMAAN Civil Engineering Club is to improve the experience of students in field civil engineering and represent themselves to the level of new emerging trends in Civil Engineering along with the arising problems like water cries, earthquakes, traffic congestion etc.",
        cat:"Tech",
          url:"https://i.pinimg.com/736x/80/50/be/8050bebdb47f4018ac213261d26d9102.jpg",
          link:"https://www.skit.ac.in/student-corner/students-s-life.html?layout=view&id=256",
          
    },

      {  id:33,
        name:"Gaming and Animation Club",
        info:"Game goals do not always require the same type of abilities and often challenge players in different ways. Some goals rely on physical skills, such as quick reflexes, precise control movements, or fast and accurate input. Other goals emphasize mental skills, including strategic thinking, problem-solving, and effective decision-making. In many games, players must also deal with randomness, where success depends on overcoming uncertain outcomes or probabilities. Together, these elements create balanced and engaging gameplay experiences.",
        cat:"Tech",
          url:"https://i.pinimg.com/1200x/50/23/ea/5023ea39b2eef7c72012e825af4a4f4f.jpg",
          link:"https://www.skit.ac.in/student-corner/students-s-life.html?layout=edit&id=1657",
          
    }
];
export default ClubInfoHome