import React from 'react'
import {LayoutDashboard, LibraryBig, User, CalendarHeart, Users, ClipboardClock, Files, Award, Image} from 'lucide-react'

const DashboardLeftSection = ({setActiveState , ActiveState}) => {
  
  return (
    <div className='bg-white outline outline-[#a4a4a4] text-[14px] w-[25%] p-5 flex gap-2 flex-col justify-start h-full rounded-2xl overflow-hidden'>
        <div onClick={()=>setActiveState('dashboard')} className={`w-full rounded-lg h-[7vh] flex items-center p-3 hover:cursor-pointer transition-all duration-200 ease-in hover:scale-102 ${ActiveState==='dashboard'? 'outline outline-[#8e2020] bg-[#8e2020] text-[#ffffff]' : 'outline outline-[#ffffff] bg-[#ffffff]'} hover:outline-[#8e2020] font-medium gap-5`}><LayoutDashboard size={20} className={`${ActiveState==='dashboard'? "text-[#ffffff]":"text-[#983530]"}`} />Dashboard</div>
         <div onClick={()=>setActiveState('club information')} className={`w-full rounded-lg h-[7vh] flex items-center p-3 hover:cursor-pointer transition-all duration-200 ease-in hover:scale-102 ${ActiveState==='club information'? 'outline outline-[#8e2020] bg-[#8e2020] text-[#ffffff]' : 'outline outline-[#ffffff] bg-[#ffffff]'} hover:outline-[#8e2020] font-medium gap-5`}><LibraryBig size={20} className={`${ActiveState==='club information'? "text-[#ffffff]":"text-[#983530]"}`} />Club Information</div>
          <div  onClick={()=>setActiveState('events')} className={`w-full rounded-lg h-[7vh] flex items-center p-3 hover:cursor-pointer transition-all duration-200 ease-in hover:scale-102 ${ActiveState==='events'? 'outline outline-[#8e2020] bg-[#8e2020] text-[#ffffff]' : 'outline outline-[#ffffff] bg-[#ffffff]'} hover:outline-[#8e2020] font-medium gap-5`}><CalendarHeart size={20} className={`${ActiveState==='events'? "text-[#ffffff]":"text-[#983530]"}`} />Events</div>
          <div onClick={()=>setActiveState('member info')} className={`w-full rounded-lg h-[7vh] flex items-center p-3 hover:cursor-pointer transition-all duration-200 ease-in hover:scale-102 ${ActiveState==='member info'? 'outline outline-[#8e2020] bg-[#8e2020] text-[#ffffff]' : 'outline outline-[#ffffff] bg-[#ffffff]'} hover:outline-[#8e2020] font-medium gap-5`}><User size={20} className={`${ActiveState==='member info'? "text-[#ffffff]":"text-[#983530]"}`} />Members Information</div>
           <div onClick={()=>setActiveState('volunteer info')} className={`w-full rounded-lg h-[7vh] flex items-center p-3 hover:cursor-pointer transition-all duration-200 ease-in hover:scale-102 ${ActiveState==='volunteer info'? 'outline outline-[#8e2020] bg-[#8e2020] text-[#ffffff]' : 'outline outline-[#ffffff] bg-[#ffffff]'} hover:outline-[#8e2020] font-medium gap-5`}><Users size={20} className={`${ActiveState==='volunteer info'? "text-[#ffffff]":"text-[#983530]"}`} />Volunteers Information</div>
            <div onClick={()=>setActiveState('pending event')} className={`w-full rounded-lg h-[7vh] flex items-center p-3 hover:cursor-pointer transition-all duration-200 ease-in hover:scale-102 ${ActiveState==='pending event'? 'outline outline-[#8e2020] bg-[#8e2020] text-[#ffffff]' : 'outline outline-[#ffffff] bg-[#ffffff]'} hover:outline-[#8e2020] font-medium gap-5`}><ClipboardClock size={20} className={`${ActiveState==='pending event'? "text-[#ffffff]":"text-[#983530]"}`} />Pending Event Request</div>
             <div  onClick={()=>setActiveState('documents')} className={`w-full rounded-lg h-[7vh] flex items-center p-3 hover:cursor-pointer transition-all duration-200 ease-in hover:scale-102 ${ActiveState==='documents'? 'outline outline-[#8e2020] bg-[#8e2020] text-[#ffffff]' : 'outline outline-[#ffffff] bg-[#ffffff]'} hover:outline-[#8e2020] font-medium gap-5`}><Files size={20} className={`${ActiveState==='documents'? "text-[#ffffff]":"text-[#983530]"}`} />Documents</div>
              <div onClick={()=>setActiveState('achivements')} className={`w-full rounded-lg h-[7vh] flex items-center p-3 hover:cursor-pointer transition-all duration-200 ease-in hover:scale-102 ${ActiveState==='achivements'? 'outline outline-[#8e2020] bg-[#8e2020] text-[#ffffff]' : 'outline outline-[#ffffff] bg-[#ffffff]'} hover:outline-[#8e2020] font-medium gap-5`}><Award size={20} className={`${ActiveState==='achivements'? "text-[#ffffff]":"text-[#983530]"}`} />Achievements and Badges</div>
               <div  onClick={()=>setActiveState('gallery')} className={`w-full rounded-lg h-[7vh] flex items-center p-3 hover:cursor-pointer transition-all duration-200 ease-in hover:scale-102 ${ActiveState==='gallery'? 'outline outline-[#8e2020] bg-[#8e2020] text-[#ffffff]' : 'outline outline-[#ffffff] bg-[#ffffff]'} hover:outline-[#8e2020] font-medium gap-5`}><Image size={20} className={`${ActiveState==='gallery'? "text-[#ffffff]":"text-[#983530]"}`} />Gallery</div>
    </div>
    
  )
  
}

export default DashboardLeftSection